'use client'
import {useSelectedLayoutSegment} from "next/navigation";


// export const metadata = {
//     title: "Home",
//     description: "Generated by create next app",
// };

export default function Layout({ children, qwerty1, qwerty2 }) {
    const esimInchSegment = useSelectedLayoutSegment('qwerty1');
    return (
        <>
            {children}
            {qwerty1}
            {qwerty2}
            <div>---===|{esimInchSegment}|===---</div>
        </>
    );
}
