// import "./globals.css";

export const metadata = {
    title: "Products items",
    description: "Generated by create next app",
};

export default function ProductLayout({ children }) {
    return (
        <div style={{backgroundColor:"#999"}}>BLA-BLIN-PRODUCTS{children}AfterChildren</div>
    );
}
